name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: premake
      run: ./premake/premake5
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
      
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: premake
      run: ./premake/premake5
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
