name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt install xorg-dev
    - name: Run Premake5
      run: ./premake/premake5 gmake2
    - name: Run Make
      run: make LDFLAGS="-Wl,--no-as-needed"
