name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt install xorg-dev
    - name: premake
      run: ./premake/premake5 gmake2
    - name: make
      run: make
      
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Enable Command Extenstions
      run: cmd /x
    - name: premake
      run: ./premake/premake5.exe gmake2
    - name: make
      run: mingw32-make CC=gcc CXX=g++
